# Generated by Django 5.0.7 on 2024-08-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_song_options_album_slug_song_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.album')),
                ('song', models.ManyToManyField(to='rest_api.song')),
            ],
        ),
    ]
